x-service-templates:
  backend-payment-api: &backend-payment-api
    image: ronaldosilva95/rinha-backend-api:v1.0
#    image: rinha-backend-api
    hostname: payment-backend
    networks:
      - payment-processor
      - backend-network
    environment:
      - JAVA_OPTS=-XX:MaxRAMPercentage=90.0 -XX:+UseContainerSupport -XX:+UseG1GC
      - PROCESSOR_DEFAULT_URL=http://payment-processor-default:8080
      - PROCESSOR_FALLBACK_URL=http://payment-processor-fallback:8080
      - METRICS_DATABASE_URL=payment-backend-metrics-db:5432/payment-metrics
      - QUEUE_THREADS=10
      - RATELIMITER_LIMIT_FOR_PERIOD=500
      - RATELIMITER_TIMEOUT_DURATION=80ms
#      - LOGGING_LEVEL_ROOT=OFF
    depends_on:
      - metrics-db
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/actuator/health" ] # Or use wget
      interval: 30s
      timeout: 1s
      retries: 2
      start_period: 20s # Time to allow the application to fully start
    deploy:
#      restart_policy:
#        condition: on-failure
#        delay: 2s
#        max_attempts: 500
#        window: 5s
      resources:
        limits:
          cpus: "0.60"
          memory: "154MB"
services:
  nginx:
    image: nginx:1.25-alpine
    container_name: rinha-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api-1
      - api-2
    ports:
      - "9999:9999"
    networks:
      - backend-network
      - payment-processor
    deploy:
      resources:
        limits:
          cpus: "0.15"
          memory: "7MB"
  api-1:
    <<: *backend-payment-api
    hostname: api01
  api-2:
    <<: *backend-payment-api
    hostname: api02
  metrics-db:
    image: postgres:17-alpine
    hostname: payment-backend-metrics-db
    networks:
      - backend-network
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=payment-metrics
    ports:
      - "5432:5432"
    deploy:
      restart_policy:
        condition: on-failure
        delay: 2s
        max_attempts: 10
        window: 5s
      resources:
        limits:
          cpus: "0.15"
          memory: "35MB"
networks:
  backend-network:
    driver: bridge
  payment-processor:
    external: true