server:
  port: 8080
  servlet:
    context-path: /

logging:
  level:
    root: OFF

payment:
  service:
    url: ${PROCESSOR_DEFAULT_URL:http://localhost:8001}
    fallback: ${PROCESSOR_FALLBACK_URL:http://localhost:8002}
  queue.threads: ${QUEUE_THREADS:10}

spring:
  datasource:
    url: jdbc:postgresql://${METRICS_DATABASE_URL:localhost:5432/payment-metrics}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


resilience4j:
  circuitbreaker:
    instances:
      cirtcuitBreakerPaymentService:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 5000
        permittedNumberOfCallsInHalfOpenState: 3
  retry:
    instances:
      retryPaymentService:
        maxAttempts: 3
        waitDuration: 1s