server:
  port: 8080
  servlet:
    context-path: /

PROCESSOR_DEFAULT_URL: http://payment-processor-default:8080
PROCESSOR_FALLBACK_URL: http://payment-processor-fallback:8080
QUEUE_THREADS: 15
RETRY_COUNT: 6
METRICS_DATABASE_URL: payment-backend-metrics-db:5432/payment-metrics

payment:
  service:
    url: ${PROCESSOR_DEFAULT_URL}
    fallback: ${PROCESSOR_FALLBACK_URL}
  queue.threads: ${QUEUE_THREADS:10}
  retry.count: ${RETRY_COUNT:2}

spring:
  datasource:
    url: jdbc:postgresql://${METRICS_DATABASE_URL}
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  hikari:
    maximum-pool-size: 20
    minimum-idle: 5
    idle-timeout: 30000
    connection-timeout: 30000
    max-lifetime: 1800000
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    jpa:
      repositories:
        bootstrap-mode: lazy

feign:
  httpclient5:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
    connectTimeout: 2000
    readTimeout: 2000
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000